ALTER TABLE events ADD COLUMN event_id TEXT;
ALTER TABLE events ADD COLUMN instance TEXT NOT NULL DEFAULT '';
ALTER TABLE events ADD COLUMN kind TEXT NOT NULL DEFAULT '';
ALTER TABLE events ADD COLUMN file_id INTEGER NOT NULL DEFAULT 0;

CREATE UNIQUE INDEX events_event_id_idx ON events(event_id) WHERE event_id IS NOT NULL;
